# Generated by Django 5.0.6 on 2024-07-06 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user_num', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TechTag',
            fields=[
                ('tech_tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tech_tag_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('user_num', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='teamfinder.member')),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('user_pw', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('block_num', models.AutoField(primary_key=True, serialize=False)),
                ('blocked_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_received', to='teamfinder.member')),
                ('from_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_sent', to='teamfinder.member')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('like_num', models.AutoField(primary_key=True, serialize=False)),
                ('from_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_sent', to='teamfinder.member')),
                ('liked_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_received', to='teamfinder.member')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_tag', models.PositiveIntegerField()),
                ('post_title', models.CharField(max_length=70)),
                ('content', models.CharField(max_length=200)),
                ('user_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamfinder.member')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=20)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('class_tag', models.PositiveIntegerField()),
                ('mbti', models.CharField(max_length=4)),
                ('interest', models.CharField(max_length=100)),
                ('user_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamfinder.member')),
            ],
        ),
        migrations.CreateModel(
            name='Scrap',
            fields=[
                ('scrap_num', models.AutoField(primary_key=True, serialize=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamfinder.post')),
                ('user_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamfinder.member')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileTechTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamfinder.profile')),
                ('tech_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamfinder.techtag')),
            ],
        ),
        migrations.CreateModel(
            name='PostTechTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateField()),
                ('now_recruit', models.BooleanField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamfinder.post')),
                ('tech_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamfinder.techtag')),
            ],
        ),
    ]
